from enum import StrEnum


class RecruiterProfileStatus(StrEnum):
    ACTIVE = "ACTIVE"
    UNVERIFIED = "UNVERIFIED"
    STALE = "STALE"
    INACTIVE = "INACTIVE"


class RecruiterRoleCategory(StrEnum):
    UNIVERSITY_RECRUITING = "UNIVERSITY_RECRUITING"
    EARLY_CAREER = "EARLY_CAREER"
    TECHNICAL_RECRUITING = "TECHNICAL_RECRUITING"
    TALENT_ACQUISITION = "TALENT_ACQUISITION"
    CAMPUS_PROGRAMS = "CAMPUS_PROGRAMS"
    UNIVERSITY_PROGRAMS = "UNIVERSITY_PROGRAMS"
    EMERGING_TALENT = "EMERGING_TALENT"
    GENERAL_RECRUITING = "GENERAL_RECRUITING"
    OTHER = "OTHER"


class RecruiterEvidenceType(StrEnum):
    EMPLOYMENT = "EMPLOYMENT"
    UNIVERSITY_RECRUITING = "UNIVERSITY_RECRUITING"
    SCHOOL_CONNECTION = "SCHOOL_CONNECTION"
    ROLE_FOCUS = "ROLE_FOCUS"
    CAMPUS_EVENT = "CAMPUS_EVENT"
    RECRUITING_ANNOUNCEMENT = "RECRUITING_ANNOUNCEMENT"
    PUBLIC_PROFILE = "PUBLIC_PROFILE"
    OTHER = "OTHER"


class RelationshipStrength(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    LIMITED_EVIDENCE = "LIMITED_EVIDENCE"


class FreshnessStatus(StrEnum):
    CURRENT = "CURRENT"
    AGING = "AGING"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"


class CampusEventType(StrEnum):
    CAREER_FAIR = "CAREER_FAIR"
    INFO_SESSION = "INFO_SESSION"
    COMPANY_VISIT = "COMPANY_VISIT"
    TECH_TALK = "TECH_TALK"
    COFFEE_CHAT = "COFFEE_CHAT"
    HACKATHON = "HACKATHON"
    RECRUITING_EVENT = "RECRUITING_EVENT"
    INTERVIEW_EVENT = "INTERVIEW_EVENT"
    OTHER = "OTHER"


class UnresolvedRecruiterReason(StrEnum):
    UNKNOWN_PERSON = "UNKNOWN_PERSON"
    AMBIGUOUS_PERSON = "AMBIGUOUS_PERSON"
    UNKNOWN_SCHOOL = "UNKNOWN_SCHOOL"
    AMBIGUOUS_SCHOOL = "AMBIGUOUS_SCHOOL"
    AMBIGUOUS_COMPANY = "AMBIGUOUS_COMPANY"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
