import type { CalendarIntegration, CalendarItem } from "@/lib/types/calendar";

/**
 * Deterministic mock calendar data. Recruiting-date items favor the companies
 * already seeded in @recruitintel/db (Stripe, Cloudflare, Figma, Netflix,
 * Datadog) so links to /companies/[slug] resolve to real records. A few
 * illustrative companies (Roblox, United Airlines, Microsoft) are included
 * without a slug purely to populate the "Upcoming Recruiting Windows" preview
 * — they render as plain text, never as a link, so nothing dead-ends.
 */
export const mockCalendarItems: CalendarItem[] = [
  // --- Recruiting dates -----------------------------------------------
  {
    id: "rd-roblox-window",
    title: "Expected internship opening window",
    date: "2026-08-18",
    endDate: "2026-08-25",
    category: "RECRUITING_DATE",
    type: "INTERNSHIP_OPENING",
    status: "ESTIMATED",
    companyName: "Roblox",
    source: { name: "Historical opening pattern (3-year model)" },
  },
  {
    id: "rd-united-confirmed",
    title: "Technology internship opening",
    date: "2026-08-24",
    category: "RECRUITING_DATE",
    type: "INTERNSHIP_OPENING",
    status: "CONFIRMED",
    companyName: "United Airlines",
    source: {
      name: "Careers page",
      url: "https://seed.recruitintel.invalid/sources/united-careers",
    },
  },
  {
    id: "rd-microsoft-historical",
    title: "Historical opening period",
    date: "2026-08-27",
    category: "RECRUITING_DATE",
    type: "INTERNSHIP_OPENING",
    status: "HISTORICAL",
    companyName: "Microsoft",
    source: { name: "Prior-cycle observation" },
  },
  {
    id: "rd-stripe-deadline",
    title: "Software Engineering Intern — application window closes",
    date: "2026-09-05",
    category: "RECRUITING_DATE",
    type: "APPLICATION_DEADLINE",
    status: "CONFIRMED",
    companyId: "10000000-0000-0000-0000-000000000001",
    companySlug: "stripe",
    companyName: "Stripe",
    source: { name: "Stripe Greenhouse board", url: "https://boards-api.greenhouse.io" },
  },
  {
    id: "rd-cloudflare-estimate",
    title: "New Grad SWE — estimated posting refresh",
    date: "2026-09-02",
    category: "RECRUITING_DATE",
    type: "NEW_GRAD_OPENING",
    status: "ESTIMATED",
    companyId: "10000000-0000-0000-0000-000000000002",
    companySlug: "cloudflare",
    companyName: "Cloudflare",
    source: { name: "Career page change-frequency model" },
  },
  {
    id: "rd-figma-deadline",
    title: "Data Science Intern — application deadline",
    date: "2026-08-30",
    category: "RECRUITING_DATE",
    type: "APPLICATION_DEADLINE",
    status: "CONFIRMED",
    companyId: "10000000-0000-0000-0000-000000000003",
    companySlug: "figma",
    companyName: "Figma",
    source: { name: "Figma Greenhouse board", url: "https://boards-api.greenhouse.io" },
  },
  {
    id: "rd-netflix-campus",
    title: "Campus info session — State University",
    date: "2026-09-10",
    category: "RECRUITING_DATE",
    type: "CAMPUS_EVENT",
    status: "CONFIRMED",
    companyId: "10000000-0000-0000-0000-000000000004",
    companySlug: "netflix",
    companyName: "Netflix",
    source: { name: "University career center listing" },
  },
  {
    id: "rd-datadog-fair",
    title: "Fall Tech Career Fair — Datadog attending",
    date: "2026-09-18",
    category: "RECRUITING_DATE",
    type: "CAREER_FAIR",
    status: "ESTIMATED",
    companyId: "10000000-0000-0000-0000-000000000005",
    companySlug: "datadog",
    companyName: "Datadog",
    source: { name: "Career fair exhibitor list (unconfirmed)" },
  },
  {
    id: "rd-netflix-historical",
    title: "Last cycle's opening window",
    date: "2026-07-14",
    category: "RECRUITING_DATE",
    type: "INTERNSHIP_OPENING",
    status: "HISTORICAL",
    companyId: "10000000-0000-0000-0000-000000000004",
    companySlug: "netflix",
    companyName: "Netflix",
    source: { name: "Prior-cycle observation" },
  },

  // --- User actions ------------------------------------------------------
  {
    id: "ac-update-resume",
    title: "Update resume for internship season",
    date: "2026-08-19",
    category: "ACTION",
    type: "UPDATE_RESUME",
    status: "USER_SCHEDULED",
    completed: false,
  },
  {
    id: "ac-roblox-research",
    title: "Research Roblox culture & recent news",
    date: "2026-08-18",
    category: "ACTION",
    type: "RESEARCH_COMPANY",
    status: "USER_SCHEDULED",
    companyName: "Roblox",
    completed: true,
  },
  {
    id: "ac-stripe-outreach",
    title: "Recruiter outreach — Stripe campus team",
    date: "2026-08-21",
    category: "ACTION",
    type: "RECRUITER_OUTREACH",
    status: "USER_SCHEDULED",
    companyId: "10000000-0000-0000-0000-000000000001",
    companySlug: "stripe",
    companyName: "Stripe",
    completed: false,
  },
  {
    id: "ac-datadog-oa",
    title: "Complete Datadog online assessment",
    date: "2026-08-29",
    category: "ACTION",
    type: "COMPLETE_OA",
    status: "USER_SCHEDULED",
    companyId: "10000000-0000-0000-0000-000000000005",
    companySlug: "datadog",
    companyName: "Datadog",
    completed: false,
  },
  {
    id: "ac-cloudflare-followup",
    title: "Follow up with Cloudflare recruiter",
    date: "2026-09-04",
    category: "ACTION",
    type: "FOLLOW_UP",
    status: "USER_SCHEDULED",
    companyId: "10000000-0000-0000-0000-000000000002",
    companySlug: "cloudflare",
    companyName: "Cloudflare",
    completed: false,
  },

  // --- Prep sessions -------------------------------------------------------
  {
    id: "ps-leetcode-graphs",
    title: "LeetCode — graph problems",
    date: "2026-08-18",
    category: "PREP_SESSION",
    type: "LEETCODE",
    status: "USER_SCHEDULED",
    completed: false,
  },
  {
    id: "ps-system-design",
    title: "System design — rate limiter walkthrough",
    date: "2026-08-20",
    category: "PREP_SESSION",
    type: "SYSTEM_DESIGN",
    status: "USER_SCHEDULED",
    completed: false,
  },
  {
    id: "ps-behavioral",
    title: "Behavioral prep — STAR stories",
    date: "2026-08-22",
    category: "PREP_SESSION",
    type: "BEHAVIORAL_PREP",
    status: "USER_SCHEDULED",
    completed: false,
  },
  {
    id: "ps-mock-interview",
    title: "Mock interview with a peer",
    date: "2026-08-26",
    category: "PREP_SESSION",
    type: "MOCK_INTERVIEW",
    status: "USER_SCHEDULED",
    completed: false,
  },
  {
    id: "ps-resume-work",
    title: "Resume deep-work session",
    date: "2026-08-19",
    category: "PREP_SESSION",
    type: "RESUME_WORK",
    status: "USER_SCHEDULED",
    completed: true,
  },
];

export const mockCalendarIntegration: CalendarIntegration = {
  provider: "google",
  status: "NOT_CONNECTED",
  sync: {
    recruitingTasks: true,
    leetcodeSessions: true,
    applicationDeadlines: true,
    careerEvents: true,
  },
};
