from enum import StrEnum


class WorkType(StrEnum):
    ATS_COLLECT = "ATS_COLLECT"
    GITHUB_SYNC = "GITHUB_SYNC"
    PUBLIC_WEB_SEARCH = "PUBLIC_WEB_SEARCH"
    PUBLIC_WEB_FETCH = "PUBLIC_WEB_FETCH"
    PUBLIC_WEB_PROCESS = "PUBLIC_WEB_PROCESS"
    RECRUITER_CAMPUS_PROJECT = "RECRUITER_CAMPUS_PROJECT"
    CALENDAR_SYNC = "CALENDAR_SYNC"
    PRIVACY_RETENTION_CLEANUP = "PRIVACY_RETENTION_CLEANUP"
    SOURCE_HEALTH_ROLLUP = "SOURCE_HEALTH_ROLLUP"
    ALERT_FANOUT = "ALERT_FANOUT"
    ALERT_EVALUATE = "ALERT_EVALUATE"
    RESUME_PARSE = "RESUME_PARSE"
    MATCH_MATERIALIZE = "MATCH_MATERIALIZE"


class WorkClass(StrEnum):
    ATS = "ATS"
    GITHUB = "GITHUB"
    WEB_SEARCH = "WEB_SEARCH"
    WEB_FETCH = "WEB_FETCH"
    PROJECTION = "PROJECTION"
    CALENDAR = "CALENDAR"
    PRIVACY = "PRIVACY"
    CONTROL = "CONTROL"
    PERSONALIZATION = "PERSONALIZATION"
    RESUME = "RESUME"


class WorkStatus(StrEnum):
    READY = "READY"
    LEASED = "LEASED"
    RUNNING = "RUNNING"
    RETRY_WAIT = "RETRY_WAIT"
    SUCCEEDED = "SUCCEEDED"
    CANCELLED = "CANCELLED"
    DEAD_LETTERED = "DEAD_LETTERED"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    POLICY_BLOCKED = "POLICY_BLOCKED"


class FailureClassification(StrEnum):
    RETRYABLE = "RETRYABLE"
    NON_RETRYABLE = "NON_RETRYABLE"
    RATE_LIMITED = "RATE_LIMITED"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    POLICY_BLOCKED = "POLICY_BLOCKED"


class CoverageStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    UNKNOWN = "UNKNOWN"
    BLOCKED = "BLOCKED"
    STALE = "STALE"
