from enum import StrEnum


class WebSearchStatus(StrEnum):
    READY = "READY"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    RATE_LIMITED = "RATE_LIMITED"
    DISABLED = "DISABLED"


class CandidateFetchStatus(StrEnum):
    PENDING = "PENDING"
    FETCHED = "FETCHED"
    UNCHANGED = "UNCHANGED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"


class RelevanceStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    RELEVANT = "RELEVANT"
    POSSIBLY_RELEVANT = "POSSIBLY_RELEVANT"
    NOT_RELEVANT = "NOT_RELEVANT"


class WebSourceClassification(StrEnum):
    COMPANY_CAREERS = "COMPANY_CAREERS"
    COMPANY_BLOG = "COMPANY_BLOG"
    COMPANY_PUBLIC_PAGE = "COMPANY_PUBLIC_PAGE"
    UNIVERSITY = "UNIVERSITY"
    FORUM = "FORUM"
    GITHUB = "GITHUB"
    PUBLIC_WEB = "PUBLIC_WEB"
    RECRUITER_PUBLIC_PAGE = "RECRUITER_PUBLIC_PAGE"
    OTHER = "OTHER"


class ReliabilityLevel(StrEnum):
    OFFICIAL = "OFFICIAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class PublicObservationType(StrEnum):
    INTERNSHIP_OPENING_SIGNAL = "INTERNSHIP_OPENING_SIGNAL"
    NEW_GRAD_OPENING_SIGNAL = "NEW_GRAD_OPENING_SIGNAL"
    APPLICATION_DATE = "APPLICATION_DATE"
    APPLICATION_DEADLINE = "APPLICATION_DEADLINE"
    CAREER_FAIR = "CAREER_FAIR"
    CAMPUS_VISIT = "CAMPUS_VISIT"
    EARLY_CAREER_PROGRAM = "EARLY_CAREER_PROGRAM"
    INTERVIEW_EXPERIENCE = "INTERVIEW_EXPERIENCE"
    RECRUITING_ANNOUNCEMENT = "RECRUITING_ANNOUNCEMENT"
    ROLE_FAMILY_SIGNAL = "ROLE_FAMILY_SIGNAL"
    SCHOOL_RECRUITING_SIGNAL = "SCHOOL_RECRUITING_SIGNAL"
    GENERAL_RECRUITING_SIGNAL = "GENERAL_RECRUITING_SIGNAL"


class DatePrecision(StrEnum):
    EXACT = "EXACT"
    RANGE = "RANGE"
    MONTH = "MONTH"
    APPROXIMATE = "APPROXIMATE"
    UNKNOWN = "UNKNOWN"


class DateCertainty(StrEnum):
    CONFIRMED = "CONFIRMED"
    ESTIMATED = "ESTIMATED"
    HISTORICAL = "HISTORICAL"
    CLAIMED = "CLAIMED"


class WebWorkType(StrEnum):
    SEARCH = "WEB_SEARCH"
    FETCH = "WEB_FETCH"
    PROCESS = "WEB_PROCESS"


class SearchResultKind(StrEnum):
    WEB = "WEB"
    NEWS = "NEWS"


class WebWorkStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
