from enum import StrEnum


class EmploymentType(StrEnum):
    FULL_TIME = "FULL_TIME"
    PART_TIME = "PART_TIME"
    CONTRACT = "CONTRACT"
    TEMPORARY = "TEMPORARY"
    INTERNSHIP = "INTERNSHIP"
    CO_OP = "CO_OP"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class RoleFamily(StrEnum):
    SOFTWARE_ENGINEERING = "SOFTWARE_ENGINEERING"
    AI_ML = "AI_ML"
    DATA_SCIENCE = "DATA_SCIENCE"
    DATA_ENGINEERING = "DATA_ENGINEERING"
    PRODUCT = "PRODUCT"
    DESIGN = "DESIGN"
    SECURITY = "SECURITY"
    CLOUD_DEVOPS = "CLOUD_DEVOPS"
    QUANT = "QUANT"
    HARDWARE = "HARDWARE"
    OTHER = "OTHER"


class ExperienceLevel(StrEnum):
    INTERNSHIP = "INTERNSHIP"
    ENTRY_LEVEL = "ENTRY_LEVEL"
    MID_LEVEL = "MID_LEVEL"
    SENIOR = "SENIOR"
    LEADERSHIP = "LEADERSHIP"
    UNKNOWN = "UNKNOWN"


class RecruitingEventType(StrEnum):
    JOB_OPENED = "JOB_OPENED"
    JOB_CHANGED = "JOB_CHANGED"
    JOB_CLOSED = "JOB_CLOSED"
    GITHUB_REPOSITORY_UPDATED = "GITHUB_REPOSITORY_UPDATED"
    INTERVIEW_QUESTION_ADDED = "INTERVIEW_QUESTION_ADDED"
    INTERVIEW_QUESTION_UPDATED = "INTERVIEW_QUESTION_UPDATED"
    INTERVIEW_REPORT_DISCOVERED = "INTERVIEW_REPORT_DISCOVERED"
    CAREER_PAGE_CHANGED = "CAREER_PAGE_CHANGED"
    CAMPUS_EVENT_DISCOVERED = "CAMPUS_EVENT_DISCOVERED"
    RECRUITING_ARTICLE_DISCOVERED = "RECRUITING_ARTICLE_DISCOVERED"
    APPLICATION_DATE_SIGNAL = "APPLICATION_DATE_SIGNAL"
    HIRING_SIGNAL = "HIRING_SIGNAL"
    RECRUITER_DISCOVERED = "RECRUITER_DISCOVERED"
    RECRUITER_ACTIVITY = "RECRUITER_ACTIVITY"
    SCHOOL_RECRUITING_SIGNAL = "SCHOOL_RECRUITING_SIGNAL"


class CollectorStage(StrEnum):
    DISCOVER = "DISCOVER"
    FETCH = "FETCH"
    NORMALIZE = "NORMALIZE"
    FINGERPRINT = "FINGERPRINT"
    PERSIST = "PERSIST"
    FINALIZE = "FINALIZE"


class JobTransition(StrEnum):
    OPENED = "OPENED"
    CHANGED = "CHANGED"
    UNCHANGED = "UNCHANGED"
    REOPENED = "REOPENED"
